namespace QueryKit.Attributes
{
    /// <summary>
    /// Excludes a property from UPDATE statements generated by QueryKit.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property)]
    public sealed class IgnoreUpdateAttribute : System.Attribute
    {
    }
}