namespace QueryKit.Attributes
{
    /// <summary>
    /// Excludes a property from INSERT statements generated by QueryKit.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property)]
    public sealed class IgnoreInsertAttribute : System.Attribute
    {
    }
}