namespace QueryKit.Attributes
{
    /// <summary>
    /// Excludes a property from SELECT lists generated by QueryKit.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property)]
    public sealed class IgnoreSelectAttribute : System.Attribute
    {
    }
}